-- DubWorks Manager — episódios, elenco por episódio e seleções emergenciais
-- 2026-10-04

create table if not exists public.projeto_episodios (
  id bigint generated by default as identity primary key,
  projeto_id bigint not null references public.projetos(id) on delete cascade,
  numero integer not null check (numero > 0),
  titulo text not null default '',
  descricao text,
  status text not null default 'nao_iniciado'
    check (status in ('nao_iniciado','aguardando','em_producao','pausado','finalizado')),
  prazo_em timestamptz,
  data_inicio date,
  data_conclusao date,
  finalizacao_manual boolean not null default false,
  registro_legado boolean not null default false,
  observacoes text,
  pasta_drive_id text,
  pasta_cortes_id text,
  pasta_entregas_id text,
  pasta_finalizado_id text,
  criado_por text,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  unique (projeto_id, numero)
);

create table if not exists public.episodio_elenco (
  id bigint generated by default as identity primary key,
  projeto_id bigint not null references public.projetos(id) on delete cascade,
  episodio_id bigint not null references public.projeto_episodios(id) on delete cascade,
  elenco_id bigint references public.elenco(id) on delete set null,
  personagem text not null,
  dublador text,
  telefone text,
  status text not null default 'pendente',
  substitui_elenco_id bigint references public.elenco(id) on delete set null,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  unique (episodio_id, personagem)
);

create table if not exists public.selecao_vagas (
  id bigint generated by default as identity primary key,
  projeto_id bigint not null references public.projetos(id) on delete cascade,
  episodio_id bigint references public.projeto_episodios(id) on delete cascade,
  episodio_elenco_id bigint references public.episodio_elenco(id) on delete set null,
  personagem text not null,
  tipo text not null default 'normal' check (tipo in ('normal','emergencial')),
  motivo text,
  dublador_anterior_id bigint references public.elenco(id) on delete set null,
  status text not null default 'aberta' check (status in ('aberta','avaliacao','encerrada')),
  prazo date,
  escopo_aprovacao text
    check (
      escopo_aprovacao is null or
      escopo_aprovacao in ('somente_episodio','a_partir_episodio','projeto_diante')
    ),
  criada_por text,
  criada_em timestamptz not null default now()
);

create table if not exists public.episodio_historico (
  id bigint generated by default as identity primary key,
  projeto_id bigint not null references public.projetos(id) on delete cascade,
  episodio_id bigint not null references public.projeto_episodios(id) on delete cascade,
  tipo text not null,
  descricao text not null,
  usuario text,
  dados jsonb not null default '{}'::jsonb,
  criado_em timestamptz not null default now()
);

alter table public.entregas_producao
  add column if not exists episodio_id bigint references public.projeto_episodios(id) on delete set null;

alter table public.whatsapp_queue
  add column if not exists episodio_id bigint references public.projeto_episodios(id) on delete set null;

create index if not exists projeto_episodios_projeto_id_idx
  on public.projeto_episodios(projeto_id, numero);

create index if not exists episodio_elenco_episodio_id_idx
  on public.episodio_elenco(episodio_id);

create index if not exists selecao_vagas_episodio_id_idx
  on public.selecao_vagas(episodio_id, status);

create index if not exists episodio_historico_episodio_id_idx
  on public.episodio_historico(episodio_id, criado_em desc);

create index if not exists entregas_producao_episodio_id_idx
  on public.entregas_producao(episodio_id);

alter table public.projeto_episodios enable row level security;
alter table public.episodio_elenco enable row level security;
alter table public.selecao_vagas enable row level security;
alter table public.episodio_historico enable row level security;

drop policy if exists projeto_episodios_select_by_project on public.projeto_episodios;
create policy projeto_episodios_select_by_project
  on public.projeto_episodios
  for select
  to authenticated
  using (app_private.can_view_project_by_id(projeto_id));

drop policy if exists projeto_episodios_insert_by_project on public.projeto_episodios;
create policy projeto_episodios_insert_by_project
  on public.projeto_episodios
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.projetos p
      where p.id = projeto_id
        and app_private.can_update_project(p.lider, p.editor)
    )
  );

drop policy if exists projeto_episodios_update_by_project on public.projeto_episodios;
create policy projeto_episodios_update_by_project
  on public.projeto_episodios
  for update
  to authenticated
  using (
    exists (
      select 1
      from public.projetos p
      where p.id = projeto_id
        and app_private.can_update_project(p.lider, p.editor)
    )
  )
  with check (
    exists (
      select 1
      from public.projetos p
      where p.id = projeto_id
        and app_private.can_update_project(p.lider, p.editor)
    )
  );

drop policy if exists projeto_episodios_delete_by_project on public.projeto_episodios;
create policy projeto_episodios_delete_by_project
  on public.projeto_episodios
  for delete
  to authenticated
  using (
    exists (
      select 1
      from public.projetos p
      where p.id = projeto_id
        and app_private.can_update_project(p.lider, p.editor)
    )
  );

drop policy if exists episodio_elenco_select_by_project on public.episodio_elenco;
create policy episodio_elenco_select_by_project
  on public.episodio_elenco
  for select
  to authenticated
  using (app_private.can_view_project_by_id(projeto_id));

drop policy if exists episodio_elenco_write_by_project on public.episodio_elenco;
create policy episodio_elenco_write_by_project
  on public.episodio_elenco
  for all
  to authenticated
  using (
    exists (
      select 1
      from public.projetos p
      where p.id = projeto_id
        and app_private.can_update_project(p.lider, p.editor)
    )
  )
  with check (
    exists (
      select 1
      from public.projetos p
      where p.id = projeto_id
        and app_private.can_update_project(p.lider, p.editor)
    )
  );

drop policy if exists selecao_vagas_select_by_project on public.selecao_vagas;
create policy selecao_vagas_select_by_project
  on public.selecao_vagas
  for select
  to authenticated
  using (app_private.can_view_project_by_id(projeto_id));

drop policy if exists selecao_vagas_write_by_project on public.selecao_vagas;
create policy selecao_vagas_write_by_project
  on public.selecao_vagas
  for all
  to authenticated
  using (
    exists (
      select 1
      from public.projetos p
      where p.id = projeto_id
        and app_private.can_update_project(p.lider, p.editor)
    )
  )
  with check (
    exists (
      select 1
      from public.projetos p
      where p.id = projeto_id
        and app_private.can_update_project(p.lider, p.editor)
    )
  );

drop policy if exists episodio_historico_select_by_project on public.episodio_historico;
create policy episodio_historico_select_by_project
  on public.episodio_historico
  for select
  to authenticated
  using (app_private.can_view_project_by_id(projeto_id));

drop policy if exists episodio_historico_insert_by_project on public.episodio_historico;
create policy episodio_historico_insert_by_project
  on public.episodio_historico
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.projetos p
      where p.id = projeto_id
        and app_private.can_update_project(p.lider, p.editor)
    )
  );

comment on column public.projeto_episodios.registro_legado is
  'True quando o episódio foi concluído antes da implantação do Manager e registrado manualmente.';
